[package]
name = "yozora-tokenizer-footnote-reference"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
yozora-core-tokenizer = { path = "../core-tokenizer" }
yozora-ast = { path = "../ast" }
yozora-character = { path = "../character" }
yozora-tokenizer-footnote-definition = { path = "../tokenizer-footnote-definition" }

[lib]
path = "src/lib.rs"
