[package]
name = "yozora-suitecases"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
yozora-core-parser = { path = "../core-parser" }
yozora-parser = { path = "../parser" }
yozora-parser-gfm = { path = "../parser-gfm" }
yozora-parser-gfm-ex = { path = "../parser-gfm-ex" }
yozora-tokenizer-inline-math = { path = "../tokenizer-inline-math" }

[lib]
path = "src/lib.rs"
