#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum UnicodePdCodePoint {
    HYPHEN_MINUS = 0x0002d,
    ARMENIAN_HYPHEN = 0x0058a,
    HEBREW_PUNCTUATION_MAQAF = 0x005be,
    CANADIAN_SYLLABICS_HYPHEN = 0x01400,
    MONGOLIAN_TODO_SOFT_HYPHEN = 0x01806,
    HYPHEN = 0x02010,
    NON_BREAKING_HYPHEN = 0x02011,
    FIGURE_DASH = 0x02012,
    EN_DASH = 0x02013,
    EM_DASH = 0x02014,
    HORIZONTAL_BAR = 0x02015,
    DOUBLE_OBLIQUE_HYPHEN = 0x02e17,
    HYPHEN_WITH_DIAERESIS = 0x02e1a,
    TWO_EM_DASH = 0x02e3a,
    THREE_EM_DASH = 0x02e3b,
    DOUBLE_HYPHEN = 0x02e40,
    OBLIQUE_HYPHEN = 0x02e5d,
    WAVE_DASH = 0x0301c,
    WAVY_DASH = 0x03030,
    KATAKANA_HIRAGANA_DOUBLE_HYPHEN = 0x030a0,
    PRESENTATION_FORM_FOR_VERTICAL_EM_DASH = 0x0fe31,
    PRESENTATION_FORM_FOR_VERTICAL_EN_DASH = 0x0fe32,
    SMALL_EM_DASH = 0x0fe58,
    SMALL_HYPHEN_MINUS = 0x0fe63,
    FULLWIDTH_HYPHEN_MINUS = 0x0ff0d,
    GARAY_HYPHEN = 0x010d6e,
    YEZIDI_HYPHENATION_MARK = 0x010ead,
}

impl UnicodePdCodePoint {
    pub const VALUES: &'static [i32] = &[
        Self::HYPHEN_MINUS as i32,
        Self::ARMENIAN_HYPHEN as i32,
        Self::HEBREW_PUNCTUATION_MAQAF as i32,
        Self::CANADIAN_SYLLABICS_HYPHEN as i32,
        Self::MONGOLIAN_TODO_SOFT_HYPHEN as i32,
        Self::HYPHEN as i32,
        Self::NON_BREAKING_HYPHEN as i32,
        Self::FIGURE_DASH as i32,
        Self::EN_DASH as i32,
        Self::EM_DASH as i32,
        Self::HORIZONTAL_BAR as i32,
        Self::DOUBLE_OBLIQUE_HYPHEN as i32,
        Self::HYPHEN_WITH_DIAERESIS as i32,
        Self::TWO_EM_DASH as i32,
        Self::THREE_EM_DASH as i32,
        Self::DOUBLE_HYPHEN as i32,
        Self::OBLIQUE_HYPHEN as i32,
        Self::WAVE_DASH as i32,
        Self::WAVY_DASH as i32,
        Self::KATAKANA_HIRAGANA_DOUBLE_HYPHEN as i32,
        Self::PRESENTATION_FORM_FOR_VERTICAL_EM_DASH as i32,
        Self::PRESENTATION_FORM_FOR_VERTICAL_EN_DASH as i32,
        Self::SMALL_EM_DASH as i32,
        Self::SMALL_HYPHEN_MINUS as i32,
        Self::FULLWIDTH_HYPHEN_MINUS as i32,
        Self::GARAY_HYPHEN as i32,
        Self::YEZIDI_HYPHENATION_MARK as i32,
    ];
}
