#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum UnicodePfCodePoint {
    RIGHT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK = 0x000bb,
    RIGHT_SINGLE_QUOTATION_MARK = 0x02019,
    RIGHT_DOUBLE_QUOTATION_MARK = 0x0201d,
    SINGLE_RIGHT_POINTING_ANGLE_QUOTATION_MARK = 0x0203a,
    RIGHT_SUBSTITUTION_BRACKET = 0x02e03,
    RIGHT_DOTTED_SUBSTITUTION_BRACKET = 0x02e05,
    RIGHT_TRANSPOSITION_BRACKET = 0x02e0a,
    RIGHT_RAISED_OMISSION_BRACKET = 0x02e0d,
    RIGHT_LOW_PARAPHRASE_BRACKET = 0x02e1d,
    RIGHT_VERTICAL_BAR_WITH_QUILL = 0x02e21,
}

impl UnicodePfCodePoint {
    pub const VALUES: &'static [i32] = &[
        Self::RIGHT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK as i32,
        Self::RIGHT_SINGLE_QUOTATION_MARK as i32,
        Self::RIGHT_DOUBLE_QUOTATION_MARK as i32,
        Self::SINGLE_RIGHT_POINTING_ANGLE_QUOTATION_MARK as i32,
        Self::RIGHT_SUBSTITUTION_BRACKET as i32,
        Self::RIGHT_DOTTED_SUBSTITUTION_BRACKET as i32,
        Self::RIGHT_TRANSPOSITION_BRACKET as i32,
        Self::RIGHT_RAISED_OMISSION_BRACKET as i32,
        Self::RIGHT_LOW_PARAPHRASE_BRACKET as i32,
        Self::RIGHT_VERTICAL_BAR_WITH_QUILL as i32,
    ];
}
