#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(i32)]
pub enum UnicodePiCodePoint {
    LEFT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK = 0x000ab,
    LEFT_SINGLE_QUOTATION_MARK = 0x02018,
    SINGLE_HIGH_REVERSED_9_QUOTATION_MARK = 0x0201b,
    LEFT_DOUBLE_QUOTATION_MARK = 0x0201c,
    DOUBLE_HIGH_REVERSED_9_QUOTATION_MARK = 0x0201f,
    SINGLE_LEFT_POINTING_ANGLE_QUOTATION_MARK = 0x02039,
    LEFT_SUBSTITUTION_BRACKET = 0x02e02,
    LEFT_DOTTED_SUBSTITUTION_BRACKET = 0x02e04,
    LEFT_TRANSPOSITION_BRACKET = 0x02e09,
    LEFT_RAISED_OMISSION_BRACKET = 0x02e0c,
    LEFT_LOW_PARAPHRASE_BRACKET = 0x02e1c,
    LEFT_VERTICAL_BAR_WITH_QUILL = 0x02e20,
}

impl UnicodePiCodePoint {
    pub const VALUES: &'static [i32] = &[
        Self::LEFT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK as i32,
        Self::LEFT_SINGLE_QUOTATION_MARK as i32,
        Self::SINGLE_HIGH_REVERSED_9_QUOTATION_MARK as i32,
        Self::LEFT_DOUBLE_QUOTATION_MARK as i32,
        Self::DOUBLE_HIGH_REVERSED_9_QUOTATION_MARK as i32,
        Self::SINGLE_LEFT_POINTING_ANGLE_QUOTATION_MARK as i32,
        Self::LEFT_SUBSTITUTION_BRACKET as i32,
        Self::LEFT_DOTTED_SUBSTITUTION_BRACKET as i32,
        Self::LEFT_TRANSPOSITION_BRACKET as i32,
        Self::LEFT_RAISED_OMISSION_BRACKET as i32,
        Self::LEFT_LOW_PARAPHRASE_BRACKET as i32,
        Self::LEFT_VERTICAL_BAR_WITH_QUILL as i32,
    ];
}
