[package]
name = "yozora-tokenizer-footnote"
version.workspace = true
edition.workspace = true
license.workspace = true
license-file.workspace = true
readme.workspace = true
description = "Yozora tokenizer for inline footnotes."
include = ["src/**"]
repository.workspace = true

[dependencies]
yozora-core-tokenizer = { version = "0.1.0", path = "../core-tokenizer" }
yozora-ast = { version = "0.1.0", path = "../ast" }
yozora-character = { version = "0.1.0", path = "../character" }
yozora-tokenizer-link = { version = "0.1.0", path = "../tokenizer-link" }

[lib]
path = "src/lib.rs"
