[package]
name = "yozora-ast-util"
version.workspace = true
edition.workspace = true
license.workspace = true
license-file.workspace = true
readme.workspace = true
description = "Utilities for working with Yozora Markdown ASTs."
include = ["src/**"]
repository.workspace = true

[dependencies]
serde_json.workspace = true
yozora-ast = { version = "0.1.0", path = "../ast" }
yozora-character = { version = "0.1.0", path = "../character" }

[lib]
path = "src/lib.rs"
