[package]
name = "yozora-parser-gfm-ex"
version.workspace = true
edition.workspace = true
license.workspace = true
license-file.workspace = true
readme.workspace = true
description = "A Markdown parser with built-in tokenizers for GitHub Flavored Markdown extensions."
include = ["src/**"]
repository.workspace = true

[dependencies]
yozora-core-parser = { version = "0.1.0", path = "../core-parser" }
yozora-ast = { version = "0.1.0", path = "../ast" }
yozora-core-tokenizer = { version = "0.1.0", path = "../core-tokenizer" }
yozora-tokenizer-autolink = { version = "0.1.0", path = "../tokenizer-autolink" }
yozora-tokenizer-autolink-extension = { version = "0.1.0", path = "../tokenizer-autolink-extension" }
yozora-tokenizer-blockquote = { version = "0.1.0", path = "../tokenizer-blockquote" }
yozora-tokenizer-break = { version = "0.1.0", path = "../tokenizer-break" }
yozora-tokenizer-definition = { version = "0.1.0", path = "../tokenizer-definition" }
yozora-tokenizer-delete = { version = "0.1.0", path = "../tokenizer-delete" }
yozora-tokenizer-emphasis = { version = "0.1.0", path = "../tokenizer-emphasis" }
yozora-tokenizer-fenced-code = { version = "0.1.0", path = "../tokenizer-fenced-code" }
yozora-tokenizer-heading = { version = "0.1.0", path = "../tokenizer-heading" }
yozora-tokenizer-html-block = { version = "0.1.0", path = "../tokenizer-html-block" }
yozora-tokenizer-html-inline = { version = "0.1.0", path = "../tokenizer-html-inline" }
yozora-tokenizer-image = { version = "0.1.0", path = "../tokenizer-image" }
yozora-tokenizer-image-reference = { version = "0.1.0", path = "../tokenizer-image-reference" }
yozora-tokenizer-indented-code = { version = "0.1.0", path = "../tokenizer-indented-code" }
yozora-tokenizer-inline-code = { version = "0.1.0", path = "../tokenizer-inline-code" }
yozora-tokenizer-link = { version = "0.1.0", path = "../tokenizer-link" }
yozora-tokenizer-link-reference = { version = "0.1.0", path = "../tokenizer-link-reference" }
yozora-tokenizer-list = { version = "0.1.0", path = "../tokenizer-list" }
yozora-tokenizer-paragraph = { version = "0.1.0", path = "../tokenizer-paragraph" }
yozora-tokenizer-setext-heading = { version = "0.1.0", path = "../tokenizer-setext-heading" }
yozora-tokenizer-table = { version = "0.1.0", path = "../tokenizer-table" }
yozora-tokenizer-text = { version = "0.1.0", path = "../tokenizer-text" }
yozora-tokenizer-thematic-break = { version = "0.1.0", path = "../tokenizer-thematic-break" }

[lib]
path = "src/lib.rs"
